{% set name = "ucimlrepo" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ucimlrepo-{{ version }}.tar.gz
  sha256: 4cff3f9e814367dd60956da999ace473197237b9fce4c07e9a689e77b4ffb59a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=1.0.0
    - certifi >=2020.12.5

test:
  imports:
    - ucimlrepo
  commands:
    - pip check
#    - python -m unittest tests/test.py # this is currently broken upstream.
  requires:
    - pip
    - python {{ python_min }}
  source_files:
    - tests

about:
  home: https://github.com/uci-ml-repo/ucimlrepo
  summary: Package to easily import datasets from the UC Irvine Machine Learning Repository into scripts and notebooks.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xDazld
